import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReduxProvider from "@/app/wrapper/ReduxProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/common-components/sidebar";
import AppTopbar from "@/common-components/topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <Toaster position="top-center"/>
        <ReduxProvider>
          <SidebarProvider className="dark">
            <AppSidebar/>
            <div className="flex w-full flex-col">
              <AppTopbar />
              {children}
            </div>
          </SidebarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
